In [1]:
import numpy as np
import torch
import torch.utils.data as torchdata
import torch.nn as nn
import torch.nn.functional as F
import torchvision

## Numerical Operations

In [90]:
# create a tensor of size (2, 2)
# Usually, use torch.tensor() instead of torch.Tensor() as the former is the (default) factory method.
A = torch.tensor([[1,2],[3,4]])
B = torch.arange(4).reshape((2,2))
# Loop through the first axis of a tensor
for a in A:
    print(a)
A.shape, B.shape, A, B

tensor([1, 2])
tensor([3, 4])


(torch.Size([2, 2]),
 torch.Size([2, 2]),
 tensor([[1, 2],
         [3, 4]]),
 tensor([[0, 1],
         [2, 3]]))

In [91]:
# Inverting a tensor of booleans
a = torch.tensor([True,False,True])
~a

tensor([False,  True, False])

In [92]:
# casting one type to the torch.DoubleTensor (aka. float64)
a = torch.tensor([True,False,True])
a.double(), a.double().type()

(tensor([1., 0., 1.], dtype=torch.float64), 'torch.DoubleTensor')

In [4]:
a = torch.tensor([True,False,True,False])
b = torch.tensor([False,True,True,False])
a | b, a & b

(tensor([ True,  True,  True, False]), tensor([False, False,  True, False]))

In [5]:
# stacking along a new axis 0
a = torch.Tensor([1,2])
b = torch.Tensor([3,4])
c = torch.Tensor([5,6])
torch.stack([a,b,c])

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [6]:
# stacking along new axis 1
torch.stack([a,b,c], dim=1)

tensor([[1., 3., 5.],
        [2., 4., 6.]])

In [7]:
# concatenating tensors together
# no new dimension is introduced
torch.cat([a, b, c])

tensor([1., 2., 3., 4., 5., 6.])

In [9]:
# convenience function to remove a row from a tensor
A = (torch.arange(8) + 1).reshape((4, 2))
a = 2
A, torch.cat([A[:a], A[a + 1:]])

(tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]),
 tensor([[1, 2],
         [3, 4],
         [7, 8]]))

In [27]:
A = torch.arange(6).reshape((2,3))
A, A.squeeze(0)

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor([[0, 1, 2],
         [3, 4, 5]]))

In [22]:
A = torch.arange(6).reshape((2,3))
A, A.shape, A.unsqueeze(0).shape, A.unsqueeze(1).shape, A.unsqueeze(2).shape

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 torch.Size([2, 3]),
 torch.Size([1, 2, 3]),
 torch.Size([2, 1, 3]),
 torch.Size([2, 3, 1]))

In [25]:
A = torch.arange(6).reshape((2,3))
A, A.shape, A.unsqueeze(-1), A.unsqueeze(-1).shape, A.unsqueeze(-2).shape

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 torch.Size([2, 3]),
 tensor([[[0],
          [1],
          [2]],
 
         [[3],
          [4],
          [5]]]),
 torch.Size([2, 3, 1]),
 torch.Size([2, 1, 3]))

In [35]:
A = torch.arange(6).reshape((2,3))
A, A.repeat((2,1)), A.repeat((1,2))

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor([[0, 1, 2],
         [3, 4, 5],
         [0, 1, 2],
         [3, 4, 5]]),
 tensor([[0, 1, 2, 0, 1, 2],
         [3, 4, 5, 3, 4, 5]]))

In [40]:
# torch.tile() is the same as Tensor.repeat()
A = torch.arange(6).reshape((2,3))
A, torch.tile(A, (2,1)), torch.tile(A, (1,2))

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor([[0, 1, 2],
         [3, 4, 5],
         [0, 1, 2],
         [3, 4, 5]]),
 tensor([[0, 1, 2, 0, 1, 2],
         [3, 4, 5, 3, 4, 5]]))

In [16]:
# Duplicating a matrix along a new axis using torch.tile()
A = torch.arange(12).reshape((3,2,2))
B = torch.tile(A.unsqueeze(2), (2, 1))
A.shape, B.shape, A, B

(torch.Size([3, 2, 2]),
 torch.Size([3, 2, 2, 2]),
 tensor([[[ 0,  1],
          [ 2,  3]],
 
         [[ 4,  5],
          [ 6,  7]],
 
         [[ 8,  9],
          [10, 11]]]),
 tensor([[[[ 0,  1],
           [ 0,  1]],
 
          [[ 2,  3],
           [ 2,  3]]],
 
 
         [[[ 4,  5],
           [ 4,  5]],
 
          [[ 6,  7],
           [ 6,  7]]],
 
 
         [[[ 8,  9],
           [ 8,  9]],
 
          [[10, 11],
           [10, 11]]]]))

In [12]:
# using sums
A = (torch.arange(8) + 1).reshape((4, 2))
torch.sum(A), torch.sum(A, dim=0), torch.sum(A, dim=1)

(tensor(36), tensor([16, 20]), tensor([ 3,  7, 11, 15]))

In [2]:
A = torch.Tensor([[1, 2], [0, 1]])
torch.matrix_exp(A)

tensor([[2.7183, 5.4366],
        [0.0000, 2.7183]])

In [3]:
A = torch.Tensor([[[1, 2], [0, 1]], [[1, 2], [0, 1]], [[1, 2], [0, 1]]])
torch.matrix_exp(A)

tensor([[[2.7183, 5.4366],
         [0.0000, 2.7183]],

        [[2.7183, 5.4366],
         [0.0000, 2.7183]],

        [[2.7183, 5.4366],
         [0.0000, 2.7183]]])

In [42]:
# Batched Matrix-matrix multiplication using np.einsum()
# Matrix-matrix multiplication
A = torch.Tensor([
    [
        [1, 2],
        [4, 2]
    ],[
        [3, 1],
        [2,-1]
    ]
])
B = torch.Tensor([
    [
        [2, 0],
        [0, -1]
    ],[
        [2, 1],
        [1, 0]
    ]
])
A[0] @ B[0], A[1] @ B[1], torch.einsum("...ij,...jk->...ik", A, B)

(tensor([[ 2., -2.],
         [ 8., -2.]]),
 tensor([[7., 3.],
         [3., 2.]]),
 tensor([[[ 2., -2.],
          [ 8., -2.]],
 
         [[ 7.,  3.],
          [ 3.,  2.]]]))

In [14]:
# Trace
A1 = torch.Tensor([[ 1, 2], [3, 4]])
A2 = torch.Tensor([[-1, 2], [3, 2]])
A3 = torch.Tensor([[ 2,-1], [3, 1]])
A4 = torch.Tensor([[ 2, 1], [1, 0]])
A = torch.stack([
    torch.stack([A1, A2]),
    torch.stack([A3, A4])])
torch.trace(A1), torch.trace(A2), torch.trace(A3), \
        torch.trace(A4), torch.einsum("...ii", A)

(tensor(5.),
 tensor(1.),
 tensor(3.),
 tensor(2.),
 tensor([[5., 1.],
         [3., 2.]]))

In [98]:
A = torch.randn(2,2,2)
values, indices = A.max(0)
values

tensor([[-1.3450,  0.3728],
        [ 0.4188, -0.8023]])

In [104]:
A = torch.randn(2,2,2).unsqueeze(0)
values, indices = A.max(0)
values

tensor([[[ 1.8009,  0.5166],
         [ 0.4627, -0.4415]],

        [[ 0.0510,  2.5605],
         [-0.6070,  0.3585]]])

## Indexing, selection and manipulating tensor shapes

In [83]:
# Indicing tensors.
# Cannot use ndarray or lists as indices. They must be integer/long tensors.
A = torch.tensor([
        [1,2],
        [3,4],
        [5,6],
        [7,8]])
ind1 = torch.tensor([[0],[1],[0],[1]])
ind2 = torch.tensor([[3],[1]])
torch.gather(A, 0, ind2), torch.gather(A, 1, ind1), torch.gather(A, 1, ind1).squeeze(1)

(tensor([[7],
         [3]]),
 tensor([[1],
         [4],
         [5],
         [8]]),
 tensor([1, 4, 5, 8]))

In [36]:
# Q_values has shape (batch=2, history=3, 2)
Q_values = torch.tensor([
    # batch
    [
        # history
        [1, 2],
        [3, 4],
        [5, 6],
    ],[
        [ 7,  8],
        [ 9, 10],
        [11, 12]
    ]
])
# actions has shape (batch=2,history=3,1)
actions = torch.tensor([
    # batch
    [
        # history
        [0],
        [1],
        [0]
    ],[
        [0],
        [0],
        [1]
    ]
])
_Q_values = Q_values.gather(2, actions).squeeze(2)
_Q_values.shape

torch.Size([2, 3])

In [69]:
# Advanced usage of torch.gather()
# Documentation for torch.gather()
# https://stackoverflow.com/questions/50999977/what-does-the-gather-function-do-in-pytorch-in-layman-terms
A = torch.tensor([
        [1,2],
        [3,4],
        [5,6],
        [7,8]])
ind1 = torch.tensor([[0,1],[3,2]])
ind2 = torch.tensor([[0,1],[1,0],[0,1]])
torch.gather(A, 0, ind1), torch.gather(A, 1, ind2)

(tensor([[1, 4],
         [7, 6]]),
 tensor([[1, 2],
         [4, 3],
         [5, 6]]))

In [75]:
# Using masks to select subtensors
A = torch.arange(6).reshape(-1, 2)
mask = torch.tensor([True,False,True])
A, A[mask]

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[0, 1],
         [4, 5]]))

In [77]:
# reshaping tensors
A = torch.Tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
A, A.reshape((2,-1))

(tensor([[[1., 2.],
          [3., 4.]],
 
         [[5., 6.],
          [7., 8.]]]),
 tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]))

In [9]:
# Selecting entries from a tensor as a vector
"""
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
"""
A = torch.arange(9).reshape(3,3)
B = torch.zeros(A.shape, dtype=torch.bool)
B[0,1] = True
B[0,2] = True
B[1,1] = True
B[2,0] = True
B, A[B]

(tensor([[False,  True,  True],
         [False,  True, False],
         [ True, False, False]]),
 tensor([1, 2, 4, 6]))

## Tensor Manipulations

In [15]:
"""Padding tensor at the end of an array
tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])
"""
A = torch.arange(12).reshape(2,3,2)
# second argument specifies padding at
# (front of n-th axis, back of n-th axis, front of axis n-1, back of axis n-1, ...)
F.pad(A, (0,3,0,2,0,1), mode='constant', value=0)

tensor([[[ 0,  1,  0,  0,  0],
         [ 2,  3,  0,  0,  0],
         [ 4,  5,  0,  0,  0],
         [ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0]],

        [[ 6,  7,  0,  0,  0],
         [ 8,  9,  0,  0,  0],
         [10, 11,  0,  0,  0],
         [ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0]],

        [[ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0]]])

In [18]:
"""Padding tensor at some parts of an array"""
A = torch.arange(12).reshape(2,3,2)
# second argument specifies padding at
# (front of n-th axis, back of n-th axis, front of axis n-1, back of axis n-1, ...)
F.pad(A, (0,3,1,0), mode='constant', value=0)

tensor([[[ 0,  0,  0,  0,  0],
         [ 0,  1,  0,  0,  0],
         [ 2,  3,  0,  0,  0],
         [ 4,  5,  0,  0,  0]],

        [[ 0,  0,  0,  0,  0],
         [ 6,  7,  0,  0,  0],
         [ 8,  9,  0,  0,  0],
         [10, 11,  0,  0,  0]]])

In [19]:
"""Padding tensor at the front of an array"""
A = torch.arange(12).reshape(2,3,2)
# second argument specifies padding at
# (front of n-th axis, back of n-th axis, front of axis n-1, back of axis n-1, ...)
F.pad(A, (3,0,2,0,1,0), mode='constant', value=0)

tensor([[[ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0]],

        [[ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  1],
         [ 0,  0,  0,  2,  3],
         [ 0,  0,  0,  4,  5]],

        [[ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  6,  7],
         [ 0,  0,  0,  8,  9],
         [ 0,  0,  0, 10, 11]]])

In [20]:
A = torch.arange(12).reshape(2,3,2)
F.pad(A, (3,0), mode='constant', value=0)

tensor([[[ 0,  0,  0,  0,  1],
         [ 0,  0,  0,  2,  3],
         [ 0,  0,  0,  4,  5]],

        [[ 0,  0,  0,  6,  7],
         [ 0,  0,  0,  8,  9],
         [ 0,  0,  0, 10, 11]]])

In [33]:
# splitting the array using np.where()
A = torch.arange(12).reshape(3, 4) - 6
A, torch.where(A < 0, -1, 0) + torch.where(A > 0, 1, 0)

(tensor([[-6, -5, -4, -3],
         [-2, -1,  0,  1],
         [ 2,  3,  4,  5]]),
 tensor([[-1, -1, -1, -1],
         [-1, -1,  0,  1],
         [ 1,  1,  1,  1]]),
 (tensor([0, 0, 0, 0, 1, 1, 1, 1]), tensor([0, 1, 2, 3, 0, 1, 2, 3])))

In [40]:
# assigning arrays using masks
A = torch.arange(12, dtype=torch.int).reshape(3, 4) - 6
B = torch.arange(12, dtype=torch.int).reshape(3, 4)
C = torch.zeros(A.shape, dtype=torch.int)
C[A < 0] = B[A < 0]
A, B, C

(tensor([[-6, -5, -4, -3],
         [-2, -1,  0,  1],
         [ 2,  3,  4,  5]], dtype=torch.int32),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]], dtype=torch.int32),
 tensor([[0, 1, 2, 3],
         [4, 5, 0, 0],
         [0, 0, 0, 0]], dtype=torch.int32))

## Torch Modules

In [54]:
criterion = nn.SmoothL1Loss()
a = torch.tensor([0,1,1,2], dtype=torch.float).reshape(2,2)
b = torch.tensor([0,1,2,0], dtype=torch.float).reshape(2,2)
loss = criterion(a, b)
loss

tensor(0.5000)