In [1]:
import torch

In [5]:
# create a tensor of size (2, 2)
A = torch.Tensor([[1,2],[3,4]])
B = torch.arange(4).reshape((2,2))
# Loop through the first axis of a tensor
for a in A:
    print(a)
A.shape, B.shape, A, B

tensor([1., 2.])
tensor([3., 4.])


(torch.Size([2, 2]),
 torch.Size([2, 2]),
 tensor([[1., 2.],
         [3., 4.]]),
 tensor([[0, 1],
         [2, 3]]))

In [5]:
# stacking along a new axis 0
a = torch.Tensor([1,2])
b = torch.Tensor([3,4])
c = torch.Tensor([5,6])
torch.stack([a,b,c])

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [6]:
# stacking along new axis 1
torch.stack([a,b,c], dim=1)

tensor([[1., 3., 5.],
        [2., 4., 6.]])

In [7]:
# concatenating tensors together
# no new dimension is introduced
torch.cat([a, b, c])

tensor([1., 2., 3., 4., 5., 6.])

In [9]:
# convenience function to remove a row from a tensor
A = (torch.arange(8) + 1).reshape((4, 2))
a = 2
A, torch.cat([A[:a], A[a + 1:]])

(tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]),
 tensor([[1, 2],
         [3, 4],
         [7, 8]]))

In [27]:
A = torch.arange(6).reshape((2,3))
A, A.squeeze(0)

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor([[0, 1, 2],
         [3, 4, 5]]))

In [22]:
A = torch.arange(6).reshape((2,3))
A, A.shape, A.unsqueeze(0).shape, A.unsqueeze(1).shape, A.unsqueeze(2).shape

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 torch.Size([2, 3]),
 torch.Size([1, 2, 3]),
 torch.Size([2, 1, 3]),
 torch.Size([2, 3, 1]))

In [25]:
A = torch.arange(6).reshape((2,3))
A, A.shape, A.unsqueeze(-1), A.unsqueeze(-1).shape, A.unsqueeze(-2).shape

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 torch.Size([2, 3]),
 tensor([[[0],
          [1],
          [2]],
 
         [[3],
          [4],
          [5]]]),
 torch.Size([2, 3, 1]),
 torch.Size([2, 1, 3]))

In [35]:
A = torch.arange(6).reshape((2,3))
A, A.repeat((2,1)), A.repeat((1,2))

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor([[0, 1, 2],
         [3, 4, 5],
         [0, 1, 2],
         [3, 4, 5]]),
 tensor([[0, 1, 2, 0, 1, 2],
         [3, 4, 5, 3, 4, 5]]))

In [40]:
# torch.tile() is the same as Tensor.repeat()
A = torch.arange(6).reshape((2,3))
A, torch.tile(A, (2,1)), torch.tile(A, (1,2))

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor([[0, 1, 2],
         [3, 4, 5],
         [0, 1, 2],
         [3, 4, 5]]),
 tensor([[0, 1, 2, 0, 1, 2],
         [3, 4, 5, 3, 4, 5]]))

In [16]:
# Duplicating a matrix along a new axis using torch.tile()
A = torch.arange(12).reshape((3,2,2))
B = torch.tile(A.unsqueeze(2), (2, 1))
A.shape, B.shape, A, B

(torch.Size([3, 2, 2]),
 torch.Size([3, 2, 2, 2]),
 tensor([[[ 0,  1],
          [ 2,  3]],
 
         [[ 4,  5],
          [ 6,  7]],
 
         [[ 8,  9],
          [10, 11]]]),
 tensor([[[[ 0,  1],
           [ 0,  1]],
 
          [[ 2,  3],
           [ 2,  3]]],
 
 
         [[[ 4,  5],
           [ 4,  5]],
 
          [[ 6,  7],
           [ 6,  7]]],
 
 
         [[[ 8,  9],
           [ 8,  9]],
 
          [[10, 11],
           [10, 11]]]]))

In [12]:
# using sums
A = (torch.arange(8) + 1).reshape((4, 2))
torch.sum(A), torch.sum(A, dim=0), torch.sum(A, dim=1)

(tensor(36), tensor([16, 20]), tensor([ 3,  7, 11, 15]))

In [41]:
A = torch.Tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
A, A.reshape((2,-1))

(tensor([[[1., 2.],
          [3., 4.]],
 
         [[5., 6.],
          [7., 8.]]]),
 tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]))

In [2]:
A = torch.Tensor([[1, 2], [0, 1]])
torch.matrix_exp(A)

tensor([[2.7183, 5.4366],
        [0.0000, 2.7183]])

In [3]:
A = torch.Tensor([[[1, 2], [0, 1]], [[1, 2], [0, 1]], [[1, 2], [0, 1]]])
torch.matrix_exp(A)

tensor([[[2.7183, 5.4366],
         [0.0000, 2.7183]],

        [[2.7183, 5.4366],
         [0.0000, 2.7183]],

        [[2.7183, 5.4366],
         [0.0000, 2.7183]]])

In [42]:
# Batched Matrix-matrix multiplication using np.einsum()
# Matrix-matrix multiplication
A = torch.Tensor([
    [
        [1, 2],
        [4, 2]
    ],[
        [3, 1],
        [2,-1]
    ]
])
B = torch.Tensor([
    [
        [2, 0],
        [0, -1]
    ],[
        [2, 1],
        [1, 0]
    ]
])
A[0] @ B[0], A[1] @ B[1], torch.einsum("...ij,...jk->...ik", A, B)

(tensor([[ 2., -2.],
         [ 8., -2.]]),
 tensor([[7., 3.],
         [3., 2.]]),
 tensor([[[ 2., -2.],
          [ 8., -2.]],
 
         [[ 7.,  3.],
          [ 3.,  2.]]]))

In [14]:
# Trace
A1 = torch.Tensor([[ 1, 2], [3, 4]])
A2 = torch.Tensor([[-1, 2], [3, 2]])
A3 = torch.Tensor([[ 2,-1], [3, 1]])
A4 = torch.Tensor([[ 2, 1], [1, 0]])
A = torch.stack([
    torch.stack([A1, A2]),
    torch.stack([A3, A4])])
torch.trace(A1), torch.trace(A2), torch.trace(A3), \
        torch.trace(A4), torch.einsum("...ii", A)

(tensor(5.),
 tensor(1.),
 tensor(3.),
 tensor(2.),
 tensor([[5., 1.],
         [3., 2.]]))