In [1]:
import numpy as np
import sympy as sp
import scipy

from numpy import array
from numpy.linalg import inv
from numpy.linalg import eig
from scipy.linalg import lu

## Function to compute and clean the matrix Q formed by eigenvectors of matrix M
## TODO: avoid div by 0 for entries with zero
def getEigVecs(M):
    M = np.linalg.eig(M)[1]
    v1 = M[:,0] * (1. / M[0,0])
    v2 = M[:,1] * (1. / M[0,1])
    v3 = M[:,2] * (1. / M[0,2])
    M = np.array([v1,v2,v3])
    M = np.around(M, decimals=4)
    M = np.matrix(M).T
    return M

## Function to compute diagonal matrix
def getDiagMatx(M):
    eigVals = np.linalg.eig(M)[0]
    n = eigVals.size
    M = np.zeros((n,n), dtype=float)
    for i in range(0,n):
        M[i,i] = eigVals[i]
    return np.matrix(M)

def getLUOfDiagMinusVal(M, l):
    n = M.shape[0]
    for i in range(0,n):
        M[i,i] -= l;
    print(M)
    M = scipy.linalg.lu(M)
    M = M[2]
    return M

## get characteristic polynomial from sympy matrix
def getCharPoly(M, l):
    n = M.shape[0]
    for i in range(0,n):
        M[i,i] = M[i,i] - l;
    p = M.det()
    return sp.factor(p)


In [2]:
M2 = np.matrix([
     [ 1, 1],
     [ 4, 1]
], dtype=float)

M3 = np.matrix([
    [   1,   3,   9],
    [   1,   3,   4],
    [    0,   0,   2]
], dtype=float)

M3_prime = np.matrix([
    [  -3,   3,  -6],
    [   6,  -6,  12],
    [   6,  -6,  10]
], dtype=float)

M4 = np.matrix([
    [   1,   0,   0,  -1],
    [   0,   1,   1,   0],
    [   0,  -1,   1,   0],
    [   1,   0,   0,   1]
], dtype=float)

getLUOfDiagMinusVal(M3, -1)

#lu(M3_prime)

# eig(M4)

# getEigVecs(M3)[:,1] * (1 / (getEigVecs(M3)[1,1] * getEigVecs(M3)[2,1]) )


[[ 2.  3.  9.]
 [ 1.  4.  4.]
 [ 0.  0.  3.]]


array([[ 2. ,  3. ,  9. ],
       [ 0. ,  2.5, -0.5],
       [ 0. ,  0. ,  3. ]])