In [1]:
import numpy as np
import sympy as sp

from numpy import array
from numpy.linalg import inv
from numpy.linalg import eig

## Function to compute and clean the matrix Q formed by eigenvectors of matrix M
def getEigVals(M):
    M = np.linalg.eig(M)[1]
    v1 = M[:,0] * (1. / M[0,0])
    v2 = M[:,1] * (1. / M[0,1])
    v3 = M[:,2] * (1. / M[0,2])
    M = np.array([v1,v2,v3])
    M = np.around(M, decimals=4)
    M = np.matrix(M).T
    return M

## get diagonal matrix; part of matrix diagonalization
## * note for Sympy we can just call `P, D = M.diagonalize()`
def getDiagMatx(M):
    A = M
    eigVals = np.linalg.eig(A)[0]
    n = eigVals.size
    A = np.zeros((n,n), dtype=float)
    for i in range(0,n):
        A[i,i] = eigVals[i]
    return np.matrix(A)

## get characteristic matrix from sympy matrix
def getCharMatx(M, l):
    n = M.shape[0]
    N = sp.Matrix(M)
    for i in range(0,n):
        N[i,i] = N[i,i] - l;
    return N

## get characteristic polynomial from sympy matrix
def getCharPoly(M, l):
    N = getCharMatx(M, l)
    p = N.det()
    return sp.factor(p)

def charMatxSubLambda(M, lamb):
    l = sp.symbols('l')
    N = getCharMatx(M,l)
    return N.subs({l: lamb})

## get characteristic matrix, then substitute lambda by lamb value and calc RREF
## * use to find (generalized) eigenvector
def charMatxSubLambdaThenRREF(M, lamb):
    return charMatxSubLambda(M, lamb).rref()

In [94]:
## Diagonization example

D = np.array(
    [[-3,0,0,0],
     [ 0,1,0,0],
     [ 0,0,1,0],
     [ 0,0,0,1]], dtype=float)

Q = np.array(
    [[ 1,-0.5, 0.5,-0.5],
     [ 0,   1,   0,   0],
     [ 1,   0,   1,   0],
     [ 0,   0,   0,   1]], dtype=float)

A = np.array(
    [[ -7, -4,  4, -4],
     [  0,  1,  0,  0],
     [ -8, -4,  5, -4],
     [  0,  0,  0,  1]], dtype=float)


Qinv = np.linalg.inv(Q)

# (Qinv * A) * Q

array([[ 2. , -0.5, -0.5, -0.5],
       [ 0. ,  1. ,  0. ,  0. ],
       [-2. , -0. ,  2. , -0. ],
       [ 0. ,  0. ,  0. ,  1. ]])

In [23]:
## Matrix multiplication

D = np.matrix(
    [[ 1,2],
     [ 3,4]])
Q = np.matrix(
    [[  2,1],
     [ -1,2]])
D * Q


matrix([[ 0,  5],
        [ 2, 11]])

In [31]:
## An exmple in Friedberg text

A = np.matrix(
    [[ 1, 1],
     [ 4, 1]], dtype=float)
Q = np.matrix(
    [[ 1, 1],
     [ 2,-2]], dtype=float)
Qinv = np.linalg.inv(Q)

# given A and matrix composed of its eigenvectors
# this product gives the corr. eigenvalues of A
(Qinv * A) * Q

matrix([[ 3.,  0.],
        [ 0., -1.]])

In [66]:
## It doesn't work because A is not diagonizable

A = np.array(
    [[ -7, -4,  4, -4],
     [  0,  1,  0,  0],
     [ -8, -4,  5, -4],
     [  0,  0,  0,  1]], dtype=float)

eigA = np.linalg.eig(A)[1]

eigVec1 = eigA[:,0]
eigVec2 = eigA[:,1]
eigVec3 = eigA[:,2]
eigVec4 = eigA[:,3]

# These are the eigenvalues for the matrix
#eigVec1 = (1. / eigVec1[0]) * eigVec1
#eigVec2 = (1. / eigVec2[0]) * eigVec2
#eigVec3 = (1. / eigVec3[0]) * eigVec3
#eigVec4 = (1. / eigVec4[0]) * eigVec4

# eigVec1

Q = np.array(
    [eigVec1,
     eigVec2,
     eigVec3,
     eigVec4]).T

Qinv = np.linalg.inv(Q)

(Qinv * A) * Q

# array([[-0.70710678, -0.4472136 , -0.57735027, -0.57735027],
#        [ 0.        ,  0.        ,  0.57735027,  0.        ],
#        [-0.70710678, -0.89442719, -0.57735027, -0.57735027],
#        [ 0.        ,  0.        ,  0.        ,  0.57735027]])

array([[-14.        ,  -2.52982213,  -3.26598632,  -3.26598632],
       [  0.        ,   0.        ,  -0.        ,   0.        ],
       [  0.        ,   6.19677335,  -0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   1.        ]])

In [13]:
A = np.matrix(
    [[ 1,2],
     [ 3,2]], dtype=float)
Q = np.matrix(
    [[  1,2],
     [ -1,3]], dtype=float)
Qinv = inv(Q)
D = np.matrix(
    [[ -1,0],
     [  0,4]], dtype=float)


(Qinv * A) * Q

# (Q * D) * Qinv


matrix([[ -1.00000000e+00,  -6.66133815e-16],
        [  0.00000000e+00,   4.00000000e+00]])

In [65]:
## 3) b)
## Finding the determinant using sympy

# lambda
l = sp.symbols('l')

M = sp.Matrix(
    [[ -l,  -2,  -3],
     [ -1, 1-l,  -1],
     [  2,   2,   5-l]])

# characteristic polynomial
p = M.det()
sp.factor(p)

-(l - 3)*(l - 2)*(l - 1)

In [63]:
## 4) b)
## Using jupyter and array manipulation to get answers
## This is the best working example I can get

M = np.matrix([
    [   7,  -4,  10],
    [   4,  -3,   8],
    [  -2,   1,  -2]
], dtype=float)

# Gives us the eigenvalues
# array([-1.,  2.,  1.])

# Gives us the eigenvectors
# eig(M)[0]

# My function gets scaled 
Q = getEigVals(M)

# Check to see if the vectors are actually eigenvectors
# np.dot(M, array([1,2,0]) )

# Obtain inverse of Q
Qinv = np.linalg.inv(Q)

# check to see if Qinv is actually the inverse of Q
# np.multiply(Q, Qinv)

# Obtain diagonal matrix corresponding to Q
D = getDiagMatx(M)

## Q * D * Qinv = M; also we can make D the new coord matrix rel to B' by making B' the ordered basis formed by the eigenvectors 
# Q * D * Qinv

Qinv * M * Q

matrix([[-1.,  0.,  0.],
        [ 0.,  2.,  0.],
        [ 0.,  0.,  1.]])

In [81]:
## Friedberg Chapt 7.1
## question 3) c)
## Finding the determinant using sympy;

# lambda
l = sp.symbols('l')

sN = sp.Matrix(
    [[   11, -4,  -5],
     [   21, -8, -11],
     [    3, -1,   0]])

# start by finding basis vectors in generalized eigenspace K_lambda=2
N = np.array(N).astype(np.float)

# Show that [1, 1, 1] is an eigenvector with eigenvalue 2
# v = np.array([1, 1, 1], dtype=float)
# N.dot(v)

# To find first basis vector v=(sN-2I)(x)
# charMatxSubLambdaThenRREF(sN, 2)

# To find second basis vector
# charMatxSubLambda(sN, 2).col_insert(3, sp.Matrix([1, 1, 1])).rref()

# Show that [1, 2, 0] is a gen. eigenvector
# v = np.array([1, 2, 0], dtype=float)
# N.dot(v)

# alternative way to find vectors 
# sN_2 = charMatxSubLambda(sN, 2)
# (sN_2 * sN_2).rref()
# a, b = sp.symbols('a, b')
# sN_2 * sp.Matrix([a+b, 2*a, 2*b])
sN_2 * sp.Matrix([1, 2, 0])

# now find basis vector in generalized eigenspace K_lambda=-1

# To find first basis vector v=(sN+1I)(x)
charMatxSubLambdaThenRREF(sN, -1)

sN * sp.Matrix([1,3,0])

Matrix([
[-1],
[-3],
[ 0]])

In [26]:
## Matrix-vector multiplication example

D = np.array(
    [[1, 2, 1],
     [0, 1, 1],
     [2, 0, 1]], dtype=float)

v = np.array([1, 2, 1], dtype=float)

D.dot(v)

array([ 6.,  3.,  3.])

In [5]:
## Friedberg Chapt 7.1
## question 3) c)
## Finding the determinant using sympy;

# lambda
l = sp.symbols('l')

A = sp.Matrix(
    [[   2,  1,  0,  0],
     [   0,  2,  1,  0],
     [   0,  0,  3,  0],
     [   0,  1, -1,  3]])

# get characteristic polynomial f(t)
getCharPoly(A, l) # char poly is f(t) = (l - 3)**2*(l - 2)**2

# get (A-3I)
charMatxSubLambda(A, 3)

# simplify nullspace N(A-3I) to get first basis vectors
charMatxSubLambdaThenRREF(A, 3)

# dead-end
# sol1 = charMatxSubLambda(A, 3).col_insert(4, sp.Matrix([-1, 1, 1, 0])).rref()

# get (A-2I)
charMatxSubLambda(A, 2)

# simplify nullspace N(A-2I) to get first basis vector
charMatxSubLambdaThenRREF(A, 2)

# validate that [1, 0, 0, 0] is eigenvector
A * sp.Matrix([1, 0, 0, 0])

# find generalized eigenvector
charMatxSubLambda(A, 2).col_insert(4, sp.Matrix([1, 0, 0, 0])).rref()

charMatxSubLambda(A, 2) * sp.Matrix([0, 1, 0, -1])

charMatxSubLambdaThenRREF(A, 3)

(Matrix([
 [1, 0, -1, 0],
 [0, 1, -1, 0],
 [0, 0,  0, 0],
 [0, 0,  0, 0]]), [0, 1])

In [6]:
## Verifying Jordan Canonical Matrix questions
## is incorrect for some reason (?)

J = np.matrix(
    [[   3,  0,  0,  0],
     [   0,  3,  0,  0],
     [   0,  0,  2,  1],
     [   0,  0,  0,  2]], dtype=float)

P = np.matrix(
    [[   1,  0,  1,  0],
     [   1,  0,  0,  1],
     [   1,  0,  0,  0],
     [   0,  1,  0, -1]], dtype=float)

Pinv = np.linalg.inv(P)

P.dot(J.dot(Pinv))

matrix([[ 2.,  1.,  0.,  0.],
        [ 0.,  2.,  1.,  0.],
        [ 0.,  0.,  3.,  0.],
        [ 0.,  1., -1.,  3.]])

In [14]:
## Verifying Jordan Canonical Matrix questions

J = np.matrix(
    [[ 2,  1,  0],
     [ 0,  2,  0],
     [ 0,  0, -1]], dtype=float)

P = np.matrix(
    [[ 1,  1,  1],
     [ 1,  2,  3],
     [ 1,  0,  0]], dtype=float)

Pinv = np.linalg.inv(P)

P.dot(J.dot(Pinv))

matrix([[ 11.,  -4.,  -5.],
        [ 21.,  -8., -11.],
        [  3.,  -1.,   0.]])

In [15]:
## Verifying Jordan Canonical Matrix questions
## is incorrect for some reason (?)

J = np.matrix(
    [[   1,  1,  0,  0],
     [   0,  1,  0,  0],
     [   0,  0,  1,  1],
     [   0,  0,  0,  1]], dtype=float)

P = np.matrix(
    [[   1,  0,  0,  0],
     [   0,  0,  1,  0],
     [   0,  1,  0,  0],
     [   0,  0,  0,  1]], dtype=float)

Pinv = np.linalg.inv(P)

P.dot(J.dot(Pinv))

matrix([[ 1.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]])